CREATE DATABASE twitchchat IF NOT EXISTS;

USE twitchchat;

CREATE TABLE IF NOT EXISTS users (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(30),
  TWITCH_SUB BOOLEAN,
  MOD_STATUS BOOLEAN
);

CREATE TABLE IF NOT EXISTS videos (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VIDEO_TITLE TEXT CHARACTER SET utf8,
  VIDEO_URL VARCHAR(255),
  CREATED_AT VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS chats (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VIDEO_TIMESTAMP VARCHAR(20),
  CHAT TEXT CHARACTER SET utf8,
  USER_ID int NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES users(id),
  VIDEO_ID int NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES videos(id)
);

LOAD DATA LOCAL INFILE '/Users/anna/Desktop/Hack Reactor/RPT_Course/anna-chat-component/db/video-data.txt'
  INTO TABLE videos;

insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('TOO LOUD THURSDAY | LOUDEST STREAM ON TWITCH!', 'https://www.twitch.tv/videos/348704017', '2018-12-14T23:35:47Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('FREAKY FRIDAY | LOUDEST STREAM ON TWITCH!', 'https://www.twitch.tv/videos/349144917', '2018-12-13T23:05:22Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('FREAKY FRIDAY | LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/349303232', '2018-12-15T06:48:33Z');

insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('METAL MONDAY | LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/350550971', '2018-12-17T23:04:27Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('THRASH TUESDAY | LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/351016741', '2018-12-18T23:18:50Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('MONTHLY GAMING STREAM | EATING GROSS JELLYBEANS EVERY 10$', 'https://www.twitch.tv/videos/351487773', '2018-12-19T23:37:44Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('COME REQUEST ANYTHING| LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/351935627', '2018-12-20T23:05:30Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('METAL BEFORE CHRISTMAS | LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/352392939', '2018-12-21T23:02:52Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('GIVEAWAY EVERY SONG/NO DONATION OR SUB PRIORITY | LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/355139526', '2018-12-27T23:05:51Z');
insert into videos (VIDEO_TITLE, VIDEO_URL, CREATED_AT) VALUES('GIVEAWAY EVERY SONG/NO DONATION OR SUB PRIORITY | LOUDEST STREAM ON TWITCH', 'https://www.twitch.tv/videos/355615294', '2018-12-28T23:06:18Z');