CREATE DATABASE twitch-chat;

USE twitch-chat;

CREATE TABLE users (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(30),
  TWITCH_SUB BOOLEAN,
  MOD_STATUS BOOLEAN
)

CREATE TABLE videos (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255),
  VIDEO_URL VARCHAR(21844),
  CHANNEL_NAME VARCHAR(255),
)

CREATE TABLE chats (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VIDEO_TIMESTAMP VARCHAR(20),
  CHAT TEXT CHARACTER SET utf8,
  TIME_POSTED DATETIME,
  FOREIGN KEY(USER_ID) REFERENCES users(id),
  FOREIGN KEY(VIDEO_ID) REFERENCES videos(id)
)

